### ISSUE TITLE
Add support for fluent assertions

### ISSUE THREAD

**Issue by SimonGeering** [FritzAndFriends/ResourceManagement#35]
@csharpfritz What are your thoughts on adding [Fluent Assertions](https://github.com/fluentassertions/fluentassertions) as a dependency with the goal of helping make unit testing easier by increasing readability of assertions?
This could form two separate PRs, the first to add the dependency, so making it available for project contributors to utilise. With subsequent PR(s) to switch over the existing unit test code.

**Comment by csharpfritz** [comment]
This looks like it would be helpful to build our unit tests. Let's move forward with starting to adopt Fluent Assertions

**Comment by SimonGeering** [comment]
Daniel I have put in a PR #39 which implements this change in all the unit test assertions. I hope I haven't jumped the gun and grabbed an item you were working on! @csharpfritz we may want to allocate issues to people if duplication of PR efforts becomes a problem :-)

**Comment by marblekirby** [comment]
Great, I had started it, but I didnt get it finished last night. Thanks, I also think we should start assigning issues.
